environment:
  global:
      MINGW_HOME: "C:\\mingw-static"
      DOWNLOAD_FOLDER: "C:\\downloads"
  matrix:
    - PYTHON_HOME: "C:\\Python27"
      PYTHON_VERSION: "2.7.8"
      ARCH: "32"

    - PYTHON_HOME: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.8"
      ARCH: "64"

    - PYTHON_HOME: "C:\\Python33"
      PYTHON_VERSION: "3.3.5"
      ARCH: "32"

    - PYTHON_HOME: "C:\\Python33-x64"
      PYTHON_VERSION: "3.3.5"
      ARCH: "64"

    - PYTHON_HOME: "C:\\Python34"
      PYTHON_VERSION: "3.4.2"
      ARCH: "32"

    - PYTHON_HOME: "C:\\Python34-x64"
      PYTHON_VERSION: "3.4.2"
      ARCH: "64"

install:
  # Install the build environment with a script that uses the environment
  # variables: we use a Python 3.4 to run the script as it needs to uncompress
  # .tar.xv archives which is not supported in Python 2.
  - "C:\\Python34-x64\\python pywinbuilder.py"

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  # Set the PATH manually for subsequent CMD commands
  - "set PATH=%PYTHON_HOME%;%PYTHON_HOME%\\Scripts;%MINGW_HOME%\\bin;%PATH%"

  # Python should be in the PATH
  - "python --version"

  # The mingw compiler should be in the PATH
  - "gcc --version"

  # Build a project that has a bunch of compiled extensions: the mingw compiler
  # should be used
  - "pip install --download-cache C:\\pip-cache tornado"

cache:
  - C:\downloads\get-pip.py
  - C:\downloads\mingw32static-2014-11.tar.xz
  - C:\downloads\mingw64static-2014-11.tar.xz
  - C:\pip-cache
